"""adding an index for user table

Revision ID: 9f87de40681c
Revises: bb440a705d5f
Create Date: 2022-01-01 09:44:15.760541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f87de40681c'
down_revision = 'bb440a705d5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name_index', 'user', ['lastname', 'name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name_index', table_name='user')
    # ### end Alembic commands ###
