"""adding last token

Revision ID: a2419600874c
Revises: a5f7f347f3e2
Create Date: 2022-01-10 09:29:30.904677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2419600874c'
down_revision = 'a5f7f347f3e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_token', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_token')
    # ### end Alembic commands ###
